dispatch_paths:
  temp: f:/websites/messages/temp
  upload_temp: f:/websites/messages/upload_temp
  upload: f:/websites/messages/upload
  download_temp: f:/websites/messages/download_temp
  download: f:/websites/messages/download

ftp_info:
  host: 192.168.1.129
  username: gavin
  password: gavin
  
ERP_path: http://localhost:3000